backend:
  name: github
  repo: dackalacbayo/shuffleph # Path to your Github repository
  branch: master # Branch to update

media_folder: static/assets/images
public_folder: assets/images

collections:
  - name: "news"
    label: "News"
    folder: "src/pages/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "events"
    label: "Events"
    folder: "src/pages/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "events"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "By", name: "by", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime",format: "LL"}
      - {label: Dates, name: dates, widget: list, fields:[{label: "Date", name: "date", widget: "date", default: "", format: "LL"}]}
      - {label: "Start time",  name: "start",  widget: "datetime", default: "", format: "hh:mma"}
      - {label: "End time",  name: "end",  widget: "datetime", default: "", format: "hh:mma"}
      - {label: "Image", name: "image", widget: "list", fields:[{label: "Images", name: "images", widget: "image"}]}
      - {label: "Description", name: "body", widget: "markdown"}
